<h1>RUB&rightarrow;PLN <?php echo $this->translate('Converter'); ?></h1>
<div class="error hide"></div>
<?php 
    $form = $this->form->prepare();
    $form->setAttribute('action', $this->url('application', array('controller'=>'index', 'action'=>'convert')));
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag($form);
?>

<div class="clear"></div>
<div class="result-converter hide">
    <span class="result-from"></span> RUB = <strong><span class="result-to"></span> PLN</strong>
</div>
<div class="clear"></div>